export const ENTITY_LABELS = {
  unit_info: 'Đơn vị',
  overview: 'Tổng quan',
  staff: 'Cán bộ',
  warehouses: 'Kho trạm xưởng',
  warehouse_images: 'Ảnh kho',
  warehouse_equipment: 'Trang bị kho',
  warehouse_inspections: 'Kiểm tra kho',
  warehouse_access: 'Ra vào kho',
  warehouse_handover: 'Giao nhận',
  warehouse_exports: 'Xuất kho',
  warehouse_imports: 'Nhập kho',
  warehouse_lightning: 'Chống sét',
  weapons: 'Vũ khí',
  tech_equipment: 'Thiết bị KT',
  vehicles: 'Phương tiện',
  materials: 'Vật tư',
};

export const ENTITY_ICONS = {
  unit_info: '🏢',
  overview: '📊',
  staff: '👤',
  warehouses: '🏭',
  warehouse_images: '🖼️',
  warehouse_equipment: '🔧',
  warehouse_inspections: '🔍',
  warehouse_access: '🚪',
  warehouse_handover: '🤝',
  warehouse_exports: '📤',
  warehouse_imports: '📥',
  warehouse_lightning: '⚡',
  weapons: '⚔️',
  tech_equipment: '💻',
  vehicles: '🚗',
  materials: '📦',
};
